### ISSUE TITLE
UI / Better Layout for checkboxes in post game table

### ISSUE THREAD

**Issue by mphox-phoxdev** [mphox-phoxdev/chronicle-sheet-filler#53]
![image](https://user-images.githubusercontent.com/17091576/94896623-cbe3f900-0442-11eb-9046-43ba00cea39d.png)

Ideally there's a title over all of those checkboxes that say "Reporting Info" and the checkbox would be to the right of the label so that it matches the appearance of the reporting form on the paizo site

**Comment by aaosuarez** [comment]
@mphox-phoxdev Do you have a screenshot of the reporting form from the paizo site to reference?

**Comment by mphox-phoxdev** [comment]
Attached to the ticket already

**Comment by aaosuarez** [comment]
The attachment is of the current app. Do you have an attachment of the paizo site?
